site_name: Keras Tuner
theme:
  name: mkdocs

docs_dir: sources
repo_url: https://github.com/keras-team/keras-tuner
edit_uri: ""
site_description: 'Documentation for Keras Tuner.'

nav:
    - Home: index.md
    - Tutorials:
      - Distributed Tuning: tutorials/distributed-tuning.md
      - Tutorial2: tutorials/tutorial2.md
    - Documentation:
      - HyperModels: documentation/hypermodels.md
      - HyperParameters: documentation/hyperparameters.md
      - Oracles: documentation/oracles.md
      - Tuners: documentation/tuners.md
    - Examples:
      - Hello World: examples/helloworld.md
    - Contributing Guide: contributing.md
